# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.flag = True
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_1.setGeometry(QtCore.QRect(0, 0, 100, 100))
        self.Btn_1.setStyleSheet("background:rgb(255, 233, 123);\n"
"font: 48pt \"Segoe Script\";")
        self.Btn_1.setText("")
        self.Btn_1.setObjectName("Btn_1")
        self.Btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_2.setGeometry(QtCore.QRect(100, 0, 100, 100))
        self.Btn_2.setStyleSheet("background:rgb(255, 233, 123);\n"
"font: 48pt \"Segoe Script\";")
        self.Btn_2.setText("")
        self.Btn_2.setObjectName("Btn_2")
        self.Btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_3.setGeometry(QtCore.QRect(200, 0, 100, 100))
        self.Btn_3.setStyleSheet("background:rgb(255, 233, 123);\n"
"font: 48pt \"Segoe Script\";")
        self.Btn_3.setText("")
        self.Btn_3.setObjectName("Btn_3")
        self.Btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_4.setGeometry(QtCore.QRect(0, 100, 100, 100))
        self.Btn_4.setStyleSheet("background:rgb(255, 233, 123);\n"
"font: 48pt \"Segoe Script\";")
        self.Btn_4.setText("")
        self.Btn_4.setObjectName("Btn_4")
        self.Btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_5.setGeometry(QtCore.QRect(100, 100, 100, 100))
        self.Btn_5.setStyleSheet("background:rgb(255, 233, 123);\n"
"font: 48pt \"Segoe Script\";")
        self.Btn_5.setText("")
        self.Btn_5.setObjectName("Btn_5")
        self.Btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_6.setGeometry(QtCore.QRect(200, 100, 100, 100))
        self.Btn_6.setStyleSheet("background:rgb(255, 233, 123);\n"
"font: 48pt \"Segoe Script\";")
        self.Btn_6.setText("")
        self.Btn_6.setObjectName("Btn_6")
        self.Btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_7.setGeometry(QtCore.QRect(0, 200, 100, 100))
        self.Btn_7.setStyleSheet("background:rgb(255, 233, 123);\n"
"font: 48pt \"Segoe Script\";")
        self.Btn_7.setText("")
        self.Btn_7.setObjectName("Btn_7")
        self.Btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_8.setGeometry(QtCore.QRect(100, 200, 100, 100))
        self.Btn_8.setStyleSheet("background:rgb(255, 233, 123);\n"
"font: 48pt \"Segoe Script\";")
        self.Btn_8.setText("")
        self.Btn_8.setObjectName("Btn_8")
        self.Btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_9.setGeometry(QtCore.QRect(200, 200, 100, 100))
        self.Btn_9.setStyleSheet("background:rgb(255, 233, 123);\n"
"font: 48pt \"Segoe Script\";")
        self.Btn_9.setText("")
        self.Btn_9.setObjectName("Btn_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.move()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TicTac"))
        
    def move(self):
        self.Btn_1.clicked.connect(lambda: self.click(self.Btn_1))
        self.Btn_2.clicked.connect(lambda: self.click(self.Btn_2))
        self.Btn_3.clicked.connect(lambda: self.click(self.Btn_3))
        self.Btn_4.clicked.connect(lambda: self.click(self.Btn_4))
        self.Btn_5.clicked.connect(lambda: self.click(self.Btn_5))
        self.Btn_6.clicked.connect(lambda: self.click(self.Btn_6))
        self.Btn_7.clicked.connect(lambda: self.click(self.Btn_7))
        self.Btn_8.clicked.connect(lambda: self.click(self.Btn_8))
        self.Btn_9.clicked.connect(lambda: self.click(self.Btn_9))

    def click(self, button:object):
        if button.text() == '':
            if self.flag:
                button.setText("X")
            else:
                button.setText("O")
            self.victory_check()
            self.flag = not self.flag
    def victory_check(self):
        self.texts = [self.Btn_1.text(), self.Btn_2.text(), self.Btn_3.text(), 
                self.Btn_4.text(), self.Btn_5.text(), self.Btn_6.text(),
                self.Btn_7.text(), self.Btn_8.text(), self.Btn_9.text()]
        self.dictionary = dict(zip(list(range(1,10)), self.texts))
        self.victory_list = [(1, 2, 3), (4, 5, 6), (7, 8, 9),
                            (1, 4, 7), (2, 5, 8), (3, 6, 9),
                            (1, 5, 9), (3, 5, 7)]
        for i in self.victory_list:
            if self.dictionary[i[0]] == self.dictionary[i[1]] == self.dictionary[i[2]] != '':
                self.message('victory')
        else:
            for i in self.dictionary:
                if self.dictionary[i] == '':
                    break
            else:
                self.message()
    
    def message(self, text:str = ''):
        end_game = QMessageBox()
        if text == 'victory':
            end_game.setWindowTitle(('Крестики ' if self.flag else 'Нолики ') + 'победили!!!')
        else:
            end_game.setWindowTitle('Ничья')
        end_game.setText('Хотите сыграть ещё?')
        end_game.setIcon(QMessageBox.Warning)
        end_game.setStandardButtons(QMessageBox.Ok|QMessageBox.Cancel)
        
        end_game.buttonClicked.connect(self.popup_action)

        ret_value = end_game.exec()
        if ret_value == QMessageBox.Ok:
            self.Btn_1.setText('')
            self.Btn_2.setText('')
            self.Btn_3.setText('')
            self.Btn_4.setText('')
            self.Btn_5.setText('')
            self.Btn_6.setText('')
            self.Btn_7.setText('')
            self.Btn_8.setText('')
            self.Btn_9.setText('')
            self.flag = False
     
    def popup_action(self, i):
        if i.text() == 'Cancel':
            sys.exit(self)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
